[CP-1] Kostiukovets (Group_fb96)
ipt-labs/crypto-FB-9 pull request #12
Opened 2021-09-28 17:44 UTC by Reijaff

2021-09-28 18:21 UTC, ipt-labs commented on cp1/kostiukovets_fb-96_cp1/Untitled.ipynb
> +    "ru_alphabet = [chr(code) for code in range(ord(\"а\"), ord(\"а\") + 32)]\n",
в завданні твердий знак не має входити до алфавіту, а в самоу тексті твердий знак треба замінювати на м'який знак.

2021-09-28 18:22 UTC, ipt-labs commented on cp1/kostiukovets_fb-96_cp1/Untitled.ipynb
> +      "2.9080400719491637\n"
дивне значення, яке не схоже на правду

2021-09-28 18:26 UTC, ipt-labs requested changes
коменти до коду + в протколі в загальній таблиці Ентропія/Надлишковість перевірте дані.

2021-09-28 19:25 UTC, Reijaff commented on cp1/kostiukovets_fb-96_cp1/Untitled.ipynb
> +      "2.9080400719491637\n"
Яке саме значення вам не подобається ?

2021-09-29 11:04 UTC, ipt-labs commented on cp1/kostiukovets_fb-96_cp1/Untitled.ipynb
> +      "2.9080400719491637\n"
2.90

2021-09-29 11:17 UTC, Reijaff commented on cp1/kostiukovets_fb-96_cp1/Untitled.ipynb
> +      "2.9080400719491637\n"
підрахунок біграм з тексту з пробілами, самі пробіли я не враховував:
"аб вг"
+ "аб"
-  "б "
- " в"
+ "вг"

2022-01-16 18:26 UTC, merged