CP-1 Prykhodko (FB-93), Shakhova (FB-93)
ipt-labs/crypto-FB-9 pull request #5
Opened 2021-09-21 09:35 UTC by andriiprykhodko96

2021-09-26 09:36 UTC, ipt-labs commented on cp1/prykhodko_FB-93_shakhova_FB-93_cp1/main.py
> +        dict[alphabet[i]]=round(text.count(alphabet[i])/len_text,5)
зачем здесь округлять?

2021-09-26 09:48 UTC, ipt-labs requested changes
файл with_spaces имеет много удаленных пробелов, что будет портить статистику.
протокол с результатами и выводами отсутствует.

2021-09-26 10:40 UTC, andriiprykhodko96 commented on cp1/prykhodko_FB-93_shakhova_FB-93_cp1/main.py
> +        dict[alphabet[i]]=round(text.count(alphabet[i])/len_text,5)
Сделал просто чтобы не записывать много чисел после запятой. Сейчас так прикинул, то можно и не округлять

2021-09-26 10:43 UTC, andriiprykhodko96 commented
> файл with_spaces имеет много удаленных пробелов, что будет портить статистику.
> протокол с результатами и выводами отсутствует.

Подскажите пожалуйста, что значит удаленный пробел?

2021-09-26 11:29 UTC, ipt-labs commented on cp1/prykhodko_FB-93_shakhova_FB-93_cp1/main.py
> +        dict[alphabet[i]]=round(text.count(alphabet[i])/len_text,5)
вы просто "очень рано" начали округлять - так вы можете существенно потерять в точности вычислений

2021-09-28 17:31 UTC, ipt-labs requested changes
в файле with_spaces все еще много пробелов, которые должны были б присутствовать - отсутствуют. в протоколе, где таблицы биграмм - можно их уменьшить в масштабе, чтоб они стали помещаться полностью на страницу, и нужны будут ваши комментарии по поводу большого количества нулей в этой таблице.

2021-09-28 21:10 UTC, andriiprykhodko96 commented
> в файле with_spaces все еще много пробелов, которые должны были б присутствовать - отсутствуют. в протоколе, где таблицы биграмм - можно их уменьшить в масштабе, чтоб они стали помещаться полностью на страницу, и нужны будут ваши комментарии по поводу большого количества нулей в этой таблице.

Исправил файл с пробелами, сделал таблицы на всю страницу

По поводу нулей, то если выводить не 4, а больше значений после запятой, в большинстве из них появятся цифры. Просто в нашем случае сделали в таблице вывод только 4 цифр чтобы нормально вместить это все на страницу Ворда

2021-09-29 11:03 UTC, merged