лаб2
ipt-labs/crypto-FB-9 pull request #56
Opened 2021-11-01 04:10 UTC by Korolevalera

2021-11-01 22:06 UTC, ripthetoilet commented
1111111111111111111111¶¶¶¶¶¶¶¶¶¶1111111111111
111111111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶111111111
1111111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1111111
11111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11111
111111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶111
1111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶11
111111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
11111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
1111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
111111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
11111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
1111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
1111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
111¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
11¶¶¶¶¶_11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
11¶¶¶¶1_____1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
11____¶1_______¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
¶¶_____111_______1¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶1
¶¶¶______11________¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶
¶¶¶¶1______11________¶¶¶¶¶¶¶¶1__¶¶¶¶¶¶¶¶¶¶¶
¶1_1¶¶1_______1_______1¶¶¶¶1____¶¶¶¶¶¶¶¶¶¶1
¶1___1¶¶________________¶¶1____¶¶¶¶¶¶¶¶¶¶¶
_¶_____1¶1_______________1____¶¶¶¶¶¶¶¶¶¶¶
_¶¶¶______11__________________¶¶¶¶¶¶¶¶¶¶1
_11¶¶1______1_________________¶¶¶¶¶¶¶¶¶
_1___¶¶1______________________1¶¶¶¶¶¶1
_¶1____¶¶1_____________________¶¶¶¶1
_¶¶1_____¶_____________________1¶¶
_¶¶¶¶___________________________¶
__¶¶¶¶1_________________________¶
__¶¶¶¶¶¶________________________¶
__¶¶¶¶¶¶1_______________________¶
__1¶¶¶¶¶¶_______________________¶
___¶¶¶¶¶¶¶______________________¶
____¶¶¶¶¶¶1_____________________¶
______11¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶

2021-11-01 22:07 UTC, ripthetoilet commented
░░░░░░░░░░░░▄▄░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░▄▄█▀▀▀███▀▀▀▄▄▄░░░░░░░░░░░
░░░░░░▄▄▀▀▄▄▄▄▄▄▄▄▄██▄▄░░████▀▀░░░░░
░░░░▄▀░░░░▀█▄░░░░▀██▀░░░▀██▄▄▀▄▄░░░░
░░▄▀░░░░░░░░░▀▀▀▀▀▀░░░░░░▀▄░▀████░░░
░▄▀░░░░░░▄█░▄▄▄▄▀▀▀▀▀▀▀▄▄▄░▀▀▀▀▀░█▄░
▄▀░░░░░░░░█▄░░░░░░░▀▀▀▀▄▄▄▀█▄░░░░░█░
█░░░░░░░░░░░░░░░░░░░░░░░░░▀░▀█░░░░░█
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░▀█░░░░█
▀▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄█
░█▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█░
░░▀▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█░░
░░░▀█▄░░░░░░░░░░░░░░░░░░░░░░░░░▄▀░░░
░░░░░░▀▄▄░░░░░░░░░░░░░░░░░░░▄▄▀░░░░░
░░░░░░░░░▀▀▄▄▄░░░░░░░░░▄▄▄▀▀░░░░░░░░
░░░░░░░░░░░░░░▀▀▀▀▀█▀▀▀░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░█████░░░░░░░░░░░░░
░░░░░░░░░░░░░░░░░█░█░░░██░░░░░░░░░░░
░░░░░░░░░░░░░░░░█░░██░░░░█░░░░░░░░░░
░░░░░░░░░░░░░░░█░░░░██░░░░█░░░░░░░░░
░░░░░░░░░░░░░░█░░░░░░██░░░░██░░░░░░░
░░░░░░░░░░░▄██░░░░░░░░██░░░░█▄░░░░░░
░░░░░░░░░░░▄█░░░░░░░░░░██░░░░█▄░░░░░
░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░░░░░░

2021-11-01 22:08 UTC, ripthetoilet commented
███████▓█████▓▓╬╬╬╬╬╬╬╬▓███▓╬╬╬╬╬╬╬▓╬╬▓█
████▓▓▓▓╬╬▓█████╬╬╬╬╬╬███▓╬╬╬╬╬╬╬╬╬╬╬╬╬█
███▓▓▓▓╬╬╬╬╬╬▓██╬╬╬╬╬╬▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
████▓▓▓╬╬╬╬╬╬╬▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
███▓█▓███████▓▓███▓╬╬╬╬╬╬▓███████▓╬╬╬╬▓█
████████████████▓█▓╬╬╬╬╬▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬█
███▓▓▓▓▓▓▓▓▓▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
████▓▓▓▓▓▓▓▓▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
███▓█▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
█████▓▓▓▓▓▓▓▓█▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
█████▓▓▓▓▓▓▓██▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
█████▓▓▓▓▓████▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
████▓█▓▓▓▓██▓▓▓▓██╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
████▓▓███▓▓▓▓▓▓▓██▓╬╬╬╬╬╬╬╬╬╬╬╬█▓╬▓╬╬▓██
█████▓███▓▓▓▓▓▓▓▓████▓▓╬╬╬╬╬╬╬█▓╬╬╬╬╬▓██
█████▓▓█▓███▓▓▓████╬▓█▓▓╬╬╬▓▓█▓╬╬╬╬╬╬███
██████▓██▓███████▓╬╬╬▓▓╬▓▓██▓╬╬╬╬╬╬╬▓███
███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬████
███████▓▓██▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓████
████████▓▓▓█████▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█████
█████████▓▓▓█▓▓▓▓▓███▓╬╬╬╬╬╬╬╬╬╬╬▓██████
██████████▓▓▓█▓▓▓▓▓██╬╬╬╬╬╬╬╬╬╬╬▓███████
███████████▓▓█▓▓▓▓███▓╬╬╬╬╬╬╬╬╬▓████████
██████████████▓▓▓███▓▓╬╬╬╬╬╬╬╬██████████
███████████████▓▓▓██▓▓╬╬╬╬╬╬▓███████████

2021-11-07 09:45 UTC, ipt-labs requested changes
ми з вами взаємодіємо в рамках процесу навчання у ВНЗ. Давайте притримуватись у спілкуванні і роботах code of conduct

2021-11-14 18:46 UTC, ipt-labs requested changes
ми з вами взаємодіємо в рамках процесу навчання у ВНЗ. Давайте притримуватись у спілкуванні і роботах code of conduct

2021-11-15 15:30 UTC, merged