Shovak_Abdullaieva_FB-93_cp1
ipt-labs/crypto-FB-9 pull request #6
Opened 2021-09-21 10:54 UTC by Slavchikkkk

Попередньо надсилаємо код і текст.

2021-09-26 10:19 UTC, ipt-labs commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +            y = -math.log2(letter/number)
делать number "глобальной" переменной - не очень удачная идея, которая кажется сыграла против Вас. при подсчете H2 Ваш "алфавит" сострит из всевозможных биграмм.

2021-09-26 10:24 UTC, ipt-labs requested changes
после проверки корректности и возможных исправлений вашего кода создайте в протоколе единую табличку значений подсчитанных энтропий и избыточности, чтоб наглядно можно было обсудить результаты. выделите самые часто встречающиеся буквы, биграммы

2021-09-26 10:51 UTC, Slavchikkkk commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +            y = -math.log2(letter/number)
Ми створювали number тільки у наших випадках в залежності від answer. Це потрібно було для підрахунку кількості букв певного тексту. Ми дійсно виводили у таблицю всі можливі значення для біграм , але результат Н2 у фіналі ділили на 2 , аби досягнути коректності і наші повторювані значення не рахувалися повторно.

2021-09-26 11:42 UTC, ipt-labs commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +def bigram(a):
аргументируйте, что использование этой функции корректно и решает нужную вычислительную задачу. меня смущает, что при выборе 3 и выборе 4 у вас строятся одинаковые массивы "arr":  вы рассматриваете биграммы "а ", " а" ? вы учитываете, что "alphabet" для некоторых экспериментов должен включать " ", а для некоторых - нет

2021-09-26 12:05 UTC, Slavchikkkk commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +def bigram(a):
Так , ми беремо до уваги варіант аа , адже масив arr  починається з нуля, відповідно у функції використовується значення alphabet[0]+i(перший ітий елемент це якраз а). Також ми враховуємо , що десь повинні бути пробіли , а десь ні . Це реалізовано якраз у наших ans. В залежності він ans ми по різному фільтруємо текст. У випадку коли в тексті нема пробілів, відповідно не рахуватиметься значення.

2021-09-26 12:10 UTC, ipt-labs commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +def bigram(a):
не "аа", а "а_"  - біграмма із двох символів - "а" і "пробіл"

2021-09-26 12:17 UTC, Slavchikkkk commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +def bigram(a):
Так, враховуємо, у масиві arr у нас записані значення від 0 до 32, а у алфавіті, на місці з індексом 32 знаходить пробіл. Отже, ми перевіряємо наявність таких пар з кожною буквою. А у пункті 4, ми прибираємо з тексту пробіли, отже при порівнянні пар «літера» та «пробіл» ентропія має значення 0.

2021-09-28 17:35 UTC, ipt-labs requested changes
в протоколі хотілось би побачили біграми, які зустрічались найчастіше, загальну таблицю із обчисленими ентропіями та відповідними надлишковостями для всіх експериментів

2021-09-28 17:41 UTC, Slavchikkkk commented on cp1/shovak_fb-93_abdullaieva_fb_93_cp1/lab_1.py
> +def bigram(a):
Звичайно так , ми ж вчора з Вами передивлялись і змінили код за Вашими рекомендаціями за допомогою range.)

2021-09-29 10:48 UTC, merged