text and code
ipt-labs/crypto-FB-9 pull request #84
Opened 2021-11-19 07:17 UTC by Slavchikkkk

2021-11-20 18:53 UTC, ipt-labs requested changes
замечания in-line в коде

2021-11-20 18:53 UTC, ipt-labs commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +        return -1
мне не нравиться идея, что тут вы возвращаете -1. это означает "ошибка.обратного нет" ? вы потом где-то делаете эту проверку? если нет, то питон прекрасно подставит -1 в дальнейшие выражения и подсчитает не то, что вы ожидаете от него.

2021-11-20 18:53 UTC, ipt-labs commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +def find_key():
у вас тут полный перебор всех вариантов возможных ключей? сколько всего есть разных вариантов просочетать (2 из 5) биграмм из ШТ с (2 из 5) биграмм языка?

2021-11-20 18:53 UTC, ipt-labs commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +
анализатор "читабельности" расшифрованного текста?

2021-11-20 19:17 UTC, Slavchikkkk commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +        return -1
Змінимо на False

2021-11-20 19:21 UTC, Slavchikkkk commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +def find_key():
С із 5 по 2 * С із 5 по 2=100. Вирішили перебрати вручну і на десь спробі у нас вийшло.

2021-11-20 19:26 UTC, Slavchikkkk commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +
Ні, то щось ми забули стерти . Ми його не реалізовували , бо в методичці було написано , що не обов’язково . Якби ми його якось робили , то напевно порівнювали частоти букв у ШТ і розшифрованому тексті + ще якийсь фактор

2021-11-24 21:08 UTC, ipt-labs commented on cp3/Shovak_FB-93_Abdullaieva_FB-93_cp3/CP3.py
> +
<img width="1092" alt="Снимок экрана 2021-11-24 в 23 05 48" src="https://user-images.githubusercontent.com/90145193/143312994-e30fa928-d93a-4505-a23d-26e62eda7aa2.png">

2021-11-24 21:10 UTC, ipt-labs commented
поверніть будь ласка ваш код до стану, коли він "вирішує задачу", а не "містить захардкожену відповідь"

2021-11-29 13:47 UTC, merged