Lab1 final
ipt-labs/crypto-FB-9 pull request #9
Opened 2021-09-23 14:34 UTC by DmitriyDanilin

2021-09-26 10:49 UTC, ipt-labs requested changes
ентропії Н2 обчтслені не вірно. щодо висновків, які наявні в протоколі - у нас були обмеження на текст - ми не включали в алфавіт литеру ё, а мали замінювати її на е.  код програми в протоколі будь ласка не наводьте, а от таблички с частотами літер і біграм- так, і щоб "було очевидно" які літери і біграми зустрічаються найчастіше. наведіть загальну табличку із значеннями ентропій, відповідних обчислених надлишковостей. для блоку роботи з coolpinkprogramm обчисліть наждишковість для кожного із трьох єкспериментів, які ви виконували

2021-09-26 15:44 UTC, DmitriyDanilin commented
Перепрошую. Я торохи не можу зрозуміти чого H2 пораховані не правильно. Під час перевірки наче все правильно. Взяв перші 100 біграм і вони складаються в текст. Можете трохи пояснити?

2021-09-26 19:01 UTC, ipt-labs commented
> Перепрошую. Я торохи не можу зрозуміти чого H2 пораховані не правильно. Під час перевірки наче все правильно. Взяв перші 100 біграм і вони складаються в текст. Можете трохи пояснити?

коли ви розглядаєте статистику літер ("однограм") - ви будуєте "найслабшу" модель, яка наближує значення "справжної" ентропії найгірше. і ви отримали результат приблизно 4. Коли ви розглядаєте покращену модель - знаходите закономірності в біграмах - ви маєте отримати значення, яке вже краще апроксимує дійсне значення ентропії, і те що ві отримали 7 - значить щось пішло не так. ще раз перевірте формули "за методичкою, тоді в коді.

2021-09-28 17:42 UTC, ipt-labs requested changes
перевірте значення надлишковостей, які наведено в протоколі - дуже вони дивні : то 10% то 60%

2021-09-29 10:51 UTC, merged